### ISSUE TITLE
Cannot find "com.tuohy.worldwindvr.WorldWindVR"

### ISSUE THREAD

**Issue by dsteinbach** [danielr2e/worldwind-vr#1]
Sorry to pester but I REALLY want to play this demo. I'm running Java 1.7 on Windows 64bit machine (Vista) and I am getting this message when running the .bat or when I paste that command straight into the console:

`Could not find or load main class com.tuohy.worldwindvr.WorldWindVR`

**Comment by danielr2e** [comment]
Not pestering at all!  I would like to know what problems people have
before we release.  Are you trying to run from the release on dropbox, or
are you building from source?

**Comment by danielr2e** [comment]
Hi again. I suspect you are trying to run the .bat file directly from the
source project.  That does not work, which I agree is confusing (and we
will fix this soon).  Try downloading the distributable from here:

https://dl.dropboxusercontent.com/u/8447350/WorldWindVR.zip

**Comment by ehaensgen** [comment]
Daniel,

   I know it has been some time since you wrote this, but I was hoping you might still have some insight into my issue.  I'm glad I saw the post about the .bat file, that at least answers that question.  However, I have also seen some posts about using the executable, which I did download and am able to run.  However, while it does show on my monitor as if I was looking through the goggles, it does not actually appear in the goggles themselves.  I have tried several different settings on the Oculus, including extending the desktop to the goggles, but it is not recognizing the movements.  I have the Oculus DK2 goggles.  I was hoping you might have some ideas that I haven't thought of yet.  Thanks in advance for any help you can provide.

**Comment by danielr2e** [comment]
Hi there!

The DK1 code indeed does not work on DK2 due to API changes.  We did get
things working on DK2, and there is another code repository on google code
that may be working (I cannot remember what state I left it in).  I will
track it down and post it when I return from vacation.

Unfortunately, we have not worked on it much lately.  There are some
unavoidable issues caused by limitations of the WorldWind code base that
related to framerate, latency and distortion that were ignorable in the DK1
days (when anything that mostly worked was breathtakingly cool) that are
becoming increasingly glaring as VR matures.  When Google finally releases
there VR version of Google Earth, which has been mentioned for years now,
this project will almost certainly be obsolete.

Daniel,

I know it has been some time since you wrote this, but I was hoping you
might still have some insight into my issue. I'm glad I saw the post about
the .bat file, that at least answers that question. However, I have also
seen some posts about using the executable, which I did download and am
able to run. However, while it does show on my monitor as if I was looking
through the goggles, it does not actually appear in the goggles themselves.
I have tried several different settings on the Oculus, including extending
the desktop to the goggles, but it is not recognizing the movements. I have
the Oculus DK2 goggles. I was hoping you might have some ideas that I
haven't thought of yet. Thanks in advance for any help you can provide.

**Comment by ehaensgen** [comment]
Thank you for the quick response.  I really appreciate you taking the time and look forward to checking out your code and building on it.

**Comment by ehaensgen** [comment]
Daniel,

   Just out of curiosity, when will you be back from vacation?  I have been studying up on the Oculus SDK, but I don't want to reinvent the wheel if I don't have to.  I will gladly share my code with you (and everyone for that matter) once I have had a chance to build on your progress.  Please let me know when you would be able to provide that to me.  I have tried looking around on google code (as time permits), but have not yet been able to find it.

Thanks,
   Eric

**Comment by danielr2e** [comment]
Eric,

Just got back!

Boy, you are not kidding about it being hard to find on Google Code.  I had
to get the search string exactly right for it to come up.  Here it is:

https://code.google.com/p/worldwind-vr/source/checkout

My recollection is that I got it working with DK2 almost just like it had
been running for DK1, and was adding support for Xbox360 controller support
when I drifted away from it.  I hope that I left it in a stable state and
it runs for you, but I can't guarantee that I did.

Daniel

**Comment by ehaensgen** [comment]
Daniel,
   That is excellent, thank you so much. I will take a look as soon as I get home tonight. Just another quick question. It has been some time since I played in Eclipse and I was wondering if you had run into the issue where it was unable to locate the world wind com object when attempting to build the project?  It looks as though everything is setup correctly, and the correct path to the com object is there, but when I try to build using the ant file it fails saying it cannot find it. Thoughts?

Thanks,

---

Eric Haensgen
Software/Web Developer, DBA

```
_____________________________
```

**Comment by ehaensgen** [comment]
Daniel,

   Sorry to keep bugging you, but I was hoping you might be able to talk more offline.  I am not sure where you are located, but I believe you have been receiving my responses via email.  I modified the above comment because I realized that it contained my personal information (phone/email), but it should still be in your email.  I live in California, and I don't get out of work until 6pm.  I was hoping you might have a few minutes to chat.  I promise after that I will leave you alone.

Thanks,
   Eric

**Comment by danielr2e** [comment]
Eric,

My apologies, this slipped my mind.  It would take me a bit to figure out
any build problems, but perhaps this will help.  I looked on my hard drive
from last year and found what I think may be a build that we generated from
the DK2 source code.  My brother wrote a script that builds it with a built
in JRE, so there is no more exe, just double click RunWorldWindVR,bat.  I
have put it on dropbox here:

https://www.dropbox.com/s/aoaq5i1db334br4/WorldWindVR-dk2.zip?dl=0

Actually, it'd be great if you could let me know if this works with DK2.  I
think it does, but I cannot fully remember :)

Daniel

**Comment by ehaensgen** [comment]
Daniel,

   I just tried the new project you sent and it worked!! I had to put the
goggles into extended mode and set the display properties to rotate -90
degrees, but once I did that the worldwindvr application opened on that
display and the tracking for the most part worked. It did lose tracking a
couple of times, but overall wasn't bad. My only concern now is that there
were graphic anomalies in the goggles. There were a lot of, for lack of a
better description, particles in the scenery. I recorded the session and
they didn't show on the video playback, so I can only assume it was
occurring during realtime rendering. I know the goggles are fine because I
am able to load some of the oculus demos without any issues. Regardless it
worked! So the code you sent me from Google, was that the source of the
compiled project you sent me via Dropbox?

Thanks,
Eric

On Tue, Jul 21, 2015 at 10:04 PM danielr2e notifications@github.com wrote:

> Eric,
> 
> My apologies, this slipped my mind. It would take me a bit to figure out
> any build problems, but perhaps this will help. I looked on my hard drive
> from last year and found what I think may be a build that we generated from
> the DK2 source code. My brother wrote a script that builds it with a built
> in JRE, so there is no more exe, just double click RunWorldWindVR,bat. I
> have put it on dropbox here:
> 
> https://www.dropbox.com/s/aoaq5i1db334br4/WorldWindVR-dk2.zip?dl=0
> 
> Actually, it'd be great if you could let me know if this works with DK2. I
> think it does, but I cannot fully remember :)
> 
> Daniel
> 
> On Wed, Jul 22, 2015 at 12:54 AM, ehaensgen notifications@github.com
> wrote:
> 
> > Daniel,
> > 
> > Sorry to keep bugging you, but I was hoping you might be able to talk
> > more
> > offline. I am not sure where you are located, but I believe you have been
> > receiving my responses via email. I modified the above comment because I
> > realized that it contained my personal information (phone/email), but it
> > should still be in your email. I live in California, and I don't get out
> > of
> > work until 6pm. I was hoping you might have a few minutes to chat. I
> > promise after that I will leave you alone.
> > 
> > Thanks,
> > Eric
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/danielr2e/worldwind-vr/issues/1#issuecomment-123562292>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/danielr2e/worldwind-vr/issues/1#issuecomment-123562981
> .
> 
> ## 
> 
> Thanks,

---

Eric Haensgen
Web Developer / DBA

Email: programgod@gmail.com

**Comment by danielr2e** [comment]
Particles, eh?  I'm not familiar with that one, and would definitely be
interested in a video showing the issue.  Is it something persistent, even
after all imagery data has been loaded?

I do remember getting the application to launch on the correct display was
a bit of a hassle.  I had a plan for dealing with it, but I very well may
never gotten around to fixing it.

What I sent you on dropbox is pretty close to what is on Google Code, but
there are probably some slight differences.

**Comment by ehaensgen** [comment]
Yea, I think the particles that I was seeing was just a one time fluke.  I have not seen it since that one time.  I took a video of it, but apparently they only showed in the goggles and not on the screen.  So far I have only been able to get this to work in Extended mode, which kind of stinks for when we want others to be able to see what is going on that are not wearing the goggles.  Something I will attempt to work out later.

I do have another question for you, sorry.  I have been working on recompiling the projects and I wanted to see if you ever ran into a similar issue.  I have contacted Oculus on this issue, but they have not been very responsive.  When attempting to recompile the LibOVR (the main project which includes LibOVRKernel) I have been getting a compilation error stating that it cannot find DMMDiag.h.  Have you run into this issue, assuming that you have tried to recompile the LibOVR project?  If so, were you ever able to find the dmmdiag.h file?  I have been searching the web like crazy and the only thing I can find is from Microsoft stating that it is part of the WDK, but every install I try does not install that file.  I am unable to recompile this project until I find this file.  Any information you could provide would be GREATLY appreciated.

**Comment by justindownes** [comment]
I am also using your DK2 project but we are running into problems where elevation data is not loading.  Have you seen this before?
